version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - docker login -u $dockerhub_username -p $dockerhub_password
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 706004250357.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sh build.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 706004250357.dkr.ecr.ap-northeast-1.amazonaws.com/cjc102-15-ecr-repo:latest
